encoder:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max : 20
decoder:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max : 20
DVAE:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max : 20
DLR:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max : 20